[package]
name = "wdid"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.101"
arboard = { version = "3.6.1", features = ["wayland-data-control"] }
calcard = "0.3"
chrono = "0.4"
chrono-tz = "0.10"
dark-light = "2.0"
directories = "6.0.0"
eframe = "0.32.0"
egui = "0.32.0"
egui_commonmark = "0.21"
git2 = "0.20.4"
image = { version = "0.25", default-features = false, features = ["png"] }
reqwest = { version = "0.12", features = ["rustls-tls"] }
rfd = "0.17.2"
rrule = "0.14"
rusqlite = { version = "0.38.0", features = ["bundled"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
thiserror = "2.0.18"
tokio = { version = "1", features = ["rt-multi-thread", "sync"] }
toml = "0.9.11"
tray-icon = "0.21"
git-commits = "0.1.0"
regex = "1.12.3"
signal-hook = "0.4.3"

[target.'cfg(target_os = "linux")'.dependencies]
gtk = "0.18"
